apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
        log stdout format raw local0
        maxconn 4096

    defaults
        mode http
        option httplog
        timeout connect 5s
        timeout client  50s
        timeout server  50s

    # Frontend utama utk traffic
    frontend http_front
        bind *:8080
        acl healthcheck path -i /healthz
        http-request return status 200 content-type text/plain string "ok" if healthcheck
        default_backend web_backends

    # Backend ke Routes (HTTPS)
    backend web_backends
        balance roundrobin
        default-server inter 3s fall 2 rise 2
        server app1 nextjs-diazluthfi07-dev.apps.rm1.0a51.p1.openshiftapps.com:443 check ssl verify none
        server app2 nextjs-adhitdn11-dev.apps.rm1.0a51.p1.openshiftapps.com:443 check ssl verify none
        server app3 nextjs-indraandriansyah-dev.apps.rm1.0a51.p1.openshiftapps.com:443 check ssl verify none
        server app4 nextjs-alexandeam-dev.apps.rm1.0a51.p1.openshiftapps.com:443 check ssl verify none
        server app5 nextjs-parhanzzz-20-dev.apps.rm1.0a51.p1.openshiftapps.com:443 check ssl verify none
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxy:2.9
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: haproxy-config-volume
          mountPath: /usr/local/etc/haproxy/haproxy.cfg
          subPath: haproxy.cfg
      volumes:
      - name: haproxy-config-volume
        configMap:
          name: haproxy-config
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy
spec:
  selector:
    app: haproxy
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: haproxy
spec:
  to:
    kind: Service
    name: haproxy
  port:
    targetPort: http
  tls:
    termination: edge