
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
        - name: nextjs
          image: diazluthfi/nextjs-app:__IMAGE_TAG__
          ports:
            - containerPort: 3000
              resources:
                requests:
                  cpu: "300m"
                  memory: "900Mi"
                limits:
                  cpu: "600m"
                  memory: "1800Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: nextjs
spec:
  selector:
    app: nextjs
  ports:
    - port: 80
      targetPort: 3000

---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nextjs
spec:
  to:
    kind: Service
    name: nextjs
  port:
    targetPort: 3000
  tls:
    termination: edge

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nextjs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nextjs
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 40




apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: bitnami/haproxy:latest
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: haproxy-config-volume
          mountPath: /bitnami/haproxy/conf/haproxy.cfg
          subPath: haproxy.cfg
      volumes:
      - name: haproxy-config-volume
        configMap:
          name: haproxy-config


apiVersion: v1
kind: Service
metadata:
  name: haproxy
spec:
  selector:
    app: haproxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000


apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
data:
  haproxy.cfg: |
    global
        log stdout format raw local0

    defaults
        mode http
        timeout connect 5s
        timeout client  50s
        timeout server  50s

    backend web_backends
        balance roundrobin
        option httpchk GET /status/200
        server app1 nextjs-diazluthfi07-dev.apps.rm1.0a51.p1.openshiftapps.com:3000 check
        server app2 nextjs-adhitdn11-dev.apps.rm1.0a51.p1.openshiftapps.com:3000 check
        server app3 nextjs-indraandriansyah-dev.apps.rm1.0a51.p1.openshiftapps.com:3000 check
        server app4 nextjs-alexandeam-dev.apps.rm1.0a51.p1.openshiftapps.com:3000 check
        server app5 nextjs-parhanzzz-20-dev.apps.rm1.0a51.p1.openshiftapps.com:3000 check


   

